// Flat ESLint config for Next.js 16 (ESLint 9).
// See https://nextjs.org/docs/app/api-reference/config/eslint
import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // --- Legacy-codebase adoption settings (2026-08-25) ---
      // The app predates these rules and carries ~400 explicit `any`
      // usages plus several new strict react-hooks rules. Downgraded to
      // warnings so CI stays green while keeping them visible; tighten
      // back to "error" as the code is cleaned up.
      "@typescript-eslint/no-explicit-any": "warn",
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/immutability": "warn",
      "react-hooks/purity": "warn",
      "react-hooks/refs": "warn",
    },
  },
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Prisma-generated model code — regenerated by `npx prisma generate`
    "src/generated/**",
  ]),
]);

export default eslintConfig;
